# Node Image from docker hub, labelled as lts-alpine 
FROM node:lts-alpine
# Set the working directory to /app
WORKDIR /app
# Copy from the directory into the volume of the container
COPY . . 
# Run the command to install the dependencies, with the production flag to only install the dependencies needed for production
RUN yarn install --production
#Run the command to start the application
CMD ["node", "src/index.js"]
# Expose the port that the application will run on
EXPOSE 3000